FROM alpine:latest
LABEL org.opencontainers.image.authors="Snowplow Data Processing Team <data-processing@snowplow.io>"

ADD build/output/linux/aws/cli/stream-replicator /root/

CMD ["/root/stream-replicator"]
