FROM --platform=$TARGETPLATFORM alpine:3.21.2
LABEL org.opencontainers.image.authors="Snowplow Analytics <support@snowplow.io>"

ARG TARGETARCH

ADD build/output/linux/aws/cli/$TARGETARCH/snowbridge /opt/snowplow/

RUN adduser -D snowplow
USER snowplow

RUN touch /tmp/config.hcl
ENV SNOWBRIDGE_CONFIG_FILE=/tmp/config.hcl

ENTRYPOINT ["/opt/snowplow/snowbridge"]
