FROM alpine:3.18.4
LABEL org.opencontainers.image.authors="Snowplow Analytics <support@snowplow.io>"

ADD build/output/linux/aws/cli/snowbridge /opt/snowplow/

RUN adduser -D snowplow
USER snowplow

ENV SNOWBRIDGE_CONFIG_FILE=/tmp/config.hcl

CMD ["/opt/snowplow/snowbridge"]
