FROM --platform=$TARGETPLATFORM alpine:3.20.0
LABEL org.opencontainers.image.authors="Snowplow Analytics <support@snowplow.io>"

ARG TARGETARCH

ADD build/output/linux/main/cli/$TARGETARCH/snowbridge /opt/snowplow/

RUN adduser -D snowplow
USER snowplow

ENV SNOWBRIDGE_CONFIG_FILE=/tmp/config.hcl

CMD ["/opt/snowplow/snowbridge"]
