FROM alpine:3.18.4
LABEL org.opencontainers.image.authors="Snowplow Analytics <support@snowplow.io>"

ADD build/output/linux/main/cli/snowbridge /opt/snowplow/

RUN apk update && apk add --no-cache openssl=3.1.4-r1

RUN adduser -D snowplow
USER snowplow

ENV SNOWBRIDGE_CONFIG_FILE=/tmp/config.hcl

CMD ["/opt/snowplow/snowbridge"]
