transform {
  use "js" {
    source_b64 = "ZnVuY3Rpb24gbWFpbihpbnB1dCkgewoKICAgIGlmIChpbnB1dC5EYXRhLmluY2x1ZGVzKCJ0ZXN0LWRhdGExIikpIHsKICAgICAgICBpbnB1dC5QYXJ0aXRpb25LZXkgPSAidGVzdC1kYXRhMSIKICAgIH0gZWxzZSBpZiAoaW5wdXQuRGF0YS5pbmNsdWRlcygidGVzdC1kYXRhMiIpKSB7CiAgICAgICAgaW5wdXQuUGFydGl0aW9uS2V5ID0gInRlc3QtZGF0YTIiCiAgICB9CgogICAgcmV0dXJuIGlucHV0Owp9"
  }
}

disable_telemetry = true