transform {
  use "lua" {
    source_b64 = "ZnVuY3Rpb24gbWFpbihpbnB1dCkKICAgIGlmIHN0cmluZy5maW5kKGlucHV0LkRhdGEsICJ0ZXN0LWRhdGExIiwgMCwgdHJ1ZSkgfj0gbmlsIHRoZW4KICAgICAgICBpbnB1dFsiUGFydGl0aW9uS2V5Il0gPSAidGVzdC1kYXRhMSIKICAgICAgICByZXR1cm4gaW5wdXQKICAgIGVsc2VpZiBzdHJpbmcuZmluZChpbnB1dC5EYXRhLCAidGVzdC1kYXRhMiIsIDAsIHRydWUpIH49IG5pbCB0aGVuCiAgICAgICAgaW5wdXRbIlBhcnRpdGlvbktleSJdID0gInRlc3QtZGF0YTIiCiAgICAgICAgcmV0dXJuIGlucHV0CiAgICBlbHNlIAogICAgICAgIHJldHVybiBpbnB1dAogICAgZW5kCmVuZA=="

    sandbox     = false # This setting preloads the json package, along with some other default packages
  }
}

disable_telemetry = true