name: ci

on:
  push:
    branches:
    - '*'
    - '*/*'
    - '**'
  workflow_call:

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    strategy:
      matrix:
        # Quotes are required: https://github.com/actions/setup-go/issues/326#issuecomment-1415719692
        go-version: ['1.25.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true

    - name: Check if go mod tidy should be run
      uses: katexochen/go-tidy-check@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.4

  test:
    name: Integration Test
    permissions:
      actions: read
      contents: read
    strategy:
      matrix:
        go-version: ['1.25.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true

    - name: Extract project version from file
      id: version
      run: |
          echo ::set-output name=VERSION::"$(cat VERSION)"

    - name: Block Concurrent Executions of Integration Tests
      if: ${{ env.NGROK_TOKEN != '' }}
      uses: softprops/turnstyle@v1
      with:
        poll-interval-seconds: 10
        same-branch-only: false
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Install ngrok
      run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          wget https://bin.ngrok.com/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz && tar -xzf ngrok-v3-stable-linux-amd64.tgz -C $GITHUB_WORKSPACE/bin
          $GITHUB_WORKSPACE/bin/ngrok authtoken ${{ secrets.NGROK_TOKEN }}

    - name: Setup integration resources
      run: export NGROK_DIR=$GITHUB_WORKSPACE/bin/ && make integration-up

    - name: Run integration & unit tests
      run: make integration-test
